### ISSUE TITLE
Pillow Installed But Not Working

### ISSUE THREAD

**Issue by bixb0012** [ponty/pyscreenshot#18]
Installed Pillow-2.7 and pyscreenshot-0.3.3 on Python 2.7.8 32-bit on Windows 7 64-bit.  pyscreenshot.grab() continued to generate error:

>>> import pyscreenshot as pss
>>> pss.grab()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\ArcGIS10.3\lib\site-packages\pyscreenshot-0.3.3-py2.7.egg\pyscreenshot\__init__.py", line 71, in grab
    return _grab(to_file=False, childprocess=childprocess, backend=backend, bbox=bbox)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\pyscreenshot-0.3.3-py2.7.egg\pyscreenshot\__init__.py", line 51, in _grab
    backend_obj = _get_loader().selected()
  File "C:\Python27\ArcGIS10.3\lib\site-packages\pyscreenshot-0.3.3-py2.7.egg\pyscreenshot\loader.py", line 75, in selected
    self.raise_exc()
  File "C:\Python27\ArcGIS10.3\lib\site-packages\pyscreenshot-0.3.3-py2.7.egg\pyscreenshot\loader.py", line 83, in raise_exc
    raise FailedBackendError(message)
pyscreenshot.loader.FailedBackendError: Install at least one backend!

Updating line 14 of pil.py to:
     from PIL import ImageGrab

Seemed to resolve the error.  That said, not sure if that will cause issues in other places.

**Comment by ponty** [comment]
I think that the global import was used in the original PIL. Pillow is a fork of PIL.
I will add support for both versions using `ImportError` exception.

**Comment by ponty** [comment]
I checked PIL and both import work, so there is no need to change your solution.
```python
import ImageGrab
```

```python
from PIL import ImageGrab
```

Thanks for the contribution!

**Comment by bixb0012** [comment]
Glad it worked out.

**Comment by F1ashhimself** [comment]
Hi there, when this will be pushed to pypi?

**Comment by kasharin** [comment]
> Hi there, when this will be pushed to pypi?

+1!

**Comment by ponty** [comment]
OK, I upload it to PyPI.

**Comment by PyPatel** [comment]
I am still getting this error. 
`  File "test_pyscreen.py", line 6, in <module> `
      `im = ImageGrab.grab()`
 ` File "/usr/local/lib/python3.5/dist-packages/pyscreenshot/__init__.py", line 46,  in grab `
        `return _grab(to_file=False, childprocess=childprocess, backend=backend, bbox=bbox)`
  ` File "/usr/local/lib/python3.5/dist-packages/pyscreenshot/__init__.py", line 29, in _grab
    return run_in_childprocess(_grab_simple, imcodec.codec, to_file, backend, bbox, filename)
  File "/usr/local/lib/python3.5/dist-packages/pyscreenshot/procutil.py", line 33, in run_in_childprocess
    raise e` 
`pyscreenshot.loader.FailedBackendError: Install at least one backend!`

I have PIL and PyQt5 and PyGTK already installed. I am working on Docker Container running on server using SSH.  @ponty I have installed using Pip from PyPI.

**Comment by wyatt009** [comment]
Hi I encountered this same problem and im already using the '0.4.2' version of pyscreenshot
