### ISSUE TITLE
Capturing only on display when there are multiple ones (Windows-specific)

### ISSUE THREAD

**Issue by starrify** [ponty/pyscreenshot#24]
### To Reproduce the Issue

In Windows, try:

```Python
import pyscreenshot
img = pyscreenshot.grab()
img.show()
```

If there are multiple displays, only the primary one would be captured.

### Tested with..

- Python 2.7.9
- The latest version of `pyscreenshot` installed from PYPI

### And with Different Platforms

- Arch Linux x86_64 with two displays: No issue.
- Windows 7 (64 bit) with two displays: This issue happens.
- Windows XP (32 bit) (inside VirtualBox) with two displays: This issue happens.

**Comment by starrify** [comment]
..Seems to be an upstream issue of `PIL`.

**Comment by ponty** [comment]
pyscreenshot is only a wrapper, first try to test the back-ends.
