### ISSUE TITLE
Full screen not being captured

### ISSUE THREAD

**Issue by gnychis** [ponty/pyscreenshot#25]
I am running Windows 10 and Python 3.4.3.

Whenever I run your full screen example:
```
$ python -m pyscreenshot.examples.showgrabfullscreen
```

I only get a partial top-left of my screen:

![pyscreenshot](https://cloud.githubusercontent.com/assets/1406044/10560033/3473e946-74cc-11e5-9436-8b9e232ef718.PNG)

If I force the size of my screen with `grab(bbox=(0,0,3200,1800))` I get the same image and pure black filling out the rest of the area:

![forced](https://cloud.githubusercontent.com/assets/1406044/10560046/ac043308-74cc-11e5-8679-2d68335e61df.png)

**Comment by ponty** [comment]
Pyscreenshot is a wrapper. It should call PIL or Pillow on Windows.
Check this code:

```python
from PIL import ImageGrab

# fullscreen
im=ImageGrab.grab()
im.show()
```

If this has the same output then it is a problem with PIL or Pillow.
Replace PIL with latest  version of Pillow.

**Comment by zlorb** [comment]
Screenshots are incorrectly cropped on high-DPI displays. Windows returns display geometry data scaled for the DPI, while the actual screenshots are unscaled. Workaround: Right-click on python.exe, Properties, Compatibility tab, check 'Disable display scaling on high DPI settings'. Repeat for pythonw.exe.

Thanks to: https://github.com/ludios/Desktopmagic

**Comment by ponty** [comment]
This problem is not related with `pyscreenshot`

**Comment by PrimordialPower** [comment]
Thank you zlorb. You solved my problem!

**Comment by uniquegodwin** [comment]
Using the following code inside your app makes your app DPI aware on Windows and solves the issue.
```
from ctypes import windll
user32 = windll.user32
user32.SetProcessDPIAware()
```

**Comment by evfredericksen** [comment]
This worked for me. Just note that `user32.SetProcessDPIAware()` needs to be called before pyscreenshot is initially imported.
