### ISSUE TITLE
PyScreenshot: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by sneakeybeakeyluke** [ponty/pyscreenshot#27]
The first screenshot taken with PyScreenshot is fine: however, after I have taken one screenshot, when I take another, the application crashes. In PyCharm, it finishes with exit code 139.
In the terminal, the output is 'Segmentation fault (core dumped)' and the application stops executing.

![untitled](https://cloud.githubusercontent.com/assets/16981205/12699736/8d797a36-c77b-11e5-9a40-fca6ba62f369.png)

**Comment by ponty** [comment]
Can you make some logging?

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by ponty** [comment]
Please try this:

```python
grab_to_file('screenshot.png', childprocess=True)
```

**Comment by pltrdy** [comment]
Hi, 

I get a similar problem:
My goal is to recongnize an item using a color. So I screenshot a box and use `getcolors()` to find my color (which is actually the second color)

```
for i in range(3):
        x = sx + i*dx
        y = sy + dy*i
        box = (x, y, x+w, y+h)
        print(box)
        im = ImageGrab.grab(bbox=box)
      
        c = ims.getcolors()
        c = sorted(c, key=lambda x: x[0], reverse=True)
        print(c[1])
        ims[i].show()

```

The output:
$sleep 5 && python3 reco.py 
(1094, 370, 1184, 425)
DEBUG:pyscreenshot.loader:forcing:None
DEBUG:pyscreenshot.loader:selecting plugin:pyqt
Gtk-Message: Failed to load module "pantheon-filechooser-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
(656, (127, 117, 0))
(1094, 435, 1184, 490)
DEBUG:pyscreenshot.loader:forcing:None
DEBUG:pyscreenshot.loader:selecting plugin:pyqt
Segmentation fault (core dumped)


I'm on Elementary OS Freya (which is basically an Ubuntu 14.04 x64 with some other stuff including different desktop mgr etc).

Even using interactive python3 CLI, I can't run Grab more than one time.
Any idea?

**Comment by ponty** [comment]
Please try the `childprocess=True` extra prameter.
If this does not help, then install scrot.

**Comment by pltrdy** [comment]
Childprocess did the job. Thx

**Comment by ponty** [comment]
childprocess parameter is True by default in the latest version

**Comment by ponty** [comment]
Fixed
