### ISSUE TITLE
Why so slow?

### ISSUE THREAD

**Issue by goncalopp** [ponty/pyscreenshot#29]
Is there any reason for the backend code to be structured around writing to files? And also on a separate process?
For backends that don't need it (gtk, qt, ...?), it seems performance would be hundreds/thousands of times better if operations are done in memory.

**Comment by goncalopp** [comment]
Example for gtk

px=gtkbuffer.get_pixels()
im= Image.frombytes('RGB', (width, height), px)

**Comment by ponty** [comment]
The only reason is that the original code was only for files, 
and it was easier just wrap all of them with the same function.
I don't plan now to reimplement with direct functions,
because I don't know the back-ends, I just wrapped existing code from others.
But any improvements as pull requests are welcome.

**Comment by ponty** [comment]
Without separate process there was errors sometimes: #26 #27
I didn't find a better solution.

**Comment by melonista** [comment]
Any hints to make capture screenshot in Linux as fast as possible? I would like to be able to process it in real time, so I need to captures at a high FPS.

**Comment by goncalopp** [comment]
@melonista I cobbled up something that was a bit faster, based in my previous comment but have since stopped working on it. I'll try to find it tomorrow and push to my fork

**Comment by ponty** [comment]
Check the documentation for performance: http://pyscreenshot.readthedocs.io/en/latest/
You can get maybe 10 fps with pyscreenshot.
You may need a video recorder like Byzanz for better performance.

**Comment by ponty** [comment]
Check the documentation for performance: http://pyscreenshot.readthedocs.io/en/latest/
You can get maybe 10 fps with pyscreenshot.
You may need a video recorder like Byzanz for better performance.
