### ISSUE TITLE
inconsistent output with small bbox and backend=imagemagick

### ISSUE THREAD

**Issue by kedabanana** [ponty/pyscreenshot#30]
When using ImageGrab.grab(bbox=box) where box is a pixel line, e.g. bbox=(100, 100, 101, 110), the resulting image seems to be incorrect. Specifically, pixel values in the "line" do not match with pixel values when a larger bbox over the same area is taken. Best explained in code:

In [17]: im = ImageGrab.grab(bbox=[100,100,101,110], backend="imagemagick")

In [18]: im2 = ImageGrab.grab(bbox=[100,100,200,200], backend="imagemagick")

In [19]: im
Out[19]: PIL.Image.Image image mode=P size=1x10 at 0x7FEC69BC0CC0

In [20]: im2
Out[20]: PIL.Image.Image image mode=RGB size=100x100 at 0x7FEC69BC0DA0

In [21]: im.load()[0,0]
Out[21]: 0

In [22]: im2.load()[0,0]
Out[22]: (31, 36, 32)

Even when converting the PIL palette image to RGB, the pixel values still seem incorrect:

In [23]: rgb = im.convert("RGB")

In [24]: rgb.load()[0,0]
Out[24]: (0, 0, 0)

This is not an issue when backend=scrot, so not a major issue. Did cause some headscratching though. 

pyscreenshot 0.4.1, ImageMagick 6.9.3-8 Q16 x86_64, linux

**Comment by ponty** [comment]
I don't understand every steps you made.
Please show me a small example program, which presents the problem.
You wrote that scrot and imagemagick backends makes different results, so 
I created a test program, which compares scrot and imagemagick backends with small bbox.
It runs without problem.

```python
from PIL import ImageChops
import pyscreenshot

backend='imagemagick'
ref = 'scrot'
bbox =(100,0,101,500)

img_ref = pyscreenshot.grab(bbox=bbox, backend=ref)
im = pyscreenshot.grab(bbox=bbox, backend=backend)

img_ref = img_ref.convert('RGB')
im = im.convert('RGB')

img_diff = ImageChops.difference(img_ref, im)

img_ref.save(ref+'.png')
im.save(backend+'.png')
img_diff.save('diff.png')

diff_bbox = img_diff.getbbox()
assert diff_bbox== None

print( 'OK')
```

**Comment by kedabanana** [comment]
Hey, below is a program that illustrates the problem on my system. Apologies for bad explanation.

When run this prints (for me):

Scrot matched: True
Imagemagick matched: False


```
#!/usr/bin/python
import pyscreenshot as ImageGrab                                                                         

# 2 bboxes, both starting at same location
large_bbox = [100,100,500,500]
small_bbox = [100,100,101,110]


# Get a bunch of images which should all contain the same pixels at [0,0]
#
# Using imagemagick
im_small = ImageGrab.grab(bbox=small_bbox, backend="imagemagick")
im_large = ImageGrab.grab(bbox=large_bbox, backend="imagemagick")

# Using scrot
sc_small = ImageGrab.grab(bbox=small_bbox, backend="scrot")
sc_large = ImageGrab.grab(bbox=large_bbox, backend="scrot")

# load() the first pixel from the small/large image for each backend. These should match?
print("Scrot matched: {}".format(sc_small.load()[0,0] == sc_large.load()[0,0]))
print("Imagemagick matched: {}".format(im_small.load()[0,0] == im_large.load()[0,0]))

```

**Comment by ponty** [comment]
Thanks, I could find the problem. Please check the latest version.

I had to change your test program with `convert`:
```python
im.convert('RGB').load()[0,0]
```

**Comment by ponty** [comment]
Fixed
