### ISSUE TITLE
dosent write image files!

### ISSUE THREAD

**Issue by its0x08** [ponty/pyscreenshot#31]
i tried it like this but the img file is not readable...

import pyscreenshot

if **name** == "**main**":

```
im = pyscreenshot.grab()
ff= open("img.png", "wb")
ff.write(im)
ff.close()
```

**Comment by ponty** [comment]
Check the pillow documentation!
http://pillow.readthedocs.io/en/3.2.x/reference/Image.html

You can save with: im.save()
```python
import pyscreenshot
im = pyscreenshot.grab()
im.save("img.png")
```

**Comment by its0x08** [comment]
Thank you!
