### ISSUE TITLE
Problem installing on Linux Mint 18.1

### ISSUE THREAD

**Issue by andreqts** [ponty/pyscreenshot#41]
I've tried to follow the same installation procedure suggested for UBUNTU, working within a virtual env with python 2.7. But after entering 'sudo pip install pyscreenshot' I've got the following error:

 Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-QUfRKj/pyscreenshot/

**Comment by andreqts** [comment]
Well, in python shell, I can successfully import setuptools. Why the installation can´t?

**Comment by andreqts** [comment]
I dont know if it can help, but I am working within a conda virtual environment. Thanks in advance.

**Comment by ponty** [comment]
Something is wrong with your Python installation.

Try to install/upgrade setuptools:
```
sudo apt-get install python-setuptools
```

```
pip install --upgrade setuptools
```
