### ISSUE TITLE
Screenshot of 3D Application is stale on Windows Server 2016 via RDP/console

### ISSUE THREAD

**Issue by zstyblik** [ponty/pyscreenshot#42]
Hello,

setup is as follows:

* Windows Server 2016
* Python 2.7.16
* Pillow==4.1.1
* pyscreenshot==0.4.2
* no Cygwin

I start user session via RDP and start 3D application. I have a small Py script which snaps screenshots in regular intervals via `ImageGrab.grab()`.

Once RDP connection is closed, session is attached to `console` in order to keep screenshots going, otherwise they cannot be grabbed and exception occurs. This works as system clock changes/progresses in pictures. However, as for 3D application, there is a still "image" from the very last time when the connection via RDP was active. This recovers once RDP connection is established again.

I don't know whether this is Windows, pyscreenshot or Pillow problem and any help will be appreciated.

Thank you.

**Comment by ponty** [comment]
If you are Windows user then you don't need pyscreenshot.
Just use ImageGrab.grab() from Pillow.
Pyscreenshot is just a wrapper around backends like Qt, GTK, Imagemagick,...
(see the documentation: http://pyscreenshot.readthedocs.io/en/latest/#hierarchy)

**Comment by zstyblik** [comment]
@ponty, you're correct and that's what I'm using. Other libraries are either pain to install or next to impossible to setup under virtualenv. Having said that, I must agree that problem(bug) most likely isn't in pyscreenshot. Still, would be nice to know what/why/how. :)

Anyway, feel free to close this issue :-s
