### ISSUE TITLE
Screenshots are cut off if windows scaling is used

### ISSUE THREAD

**Issue by kyl3r92** [ponty/pyscreenshot#63]
If I set my scaling to 125% (1440p monitor) the image is cut off on the right side. A few hundred pixels. If I change this setting to 100% it captures the whole screen as expected. 

If I use the parameters:

```
    # part of the screen
    im = ImageGrab.grab(bbox=(0, 0, 3000, 3000)) # X1,Y1,X2,Y2
    im.show()
```

It will only grab additional black pixels, the missing parts do not show up. 
I would expect the screenshot to grab the correct part of the image.

**Comment by ponty** [comment]
Please provide more information: OS, Python version, log.

Turn on logging:
```python
import logging
logging.basicConfig(level=logging.DEBUG)
```
