### ISSUE TITLE
Why Pillow not installing with package

### ISSUE THREAD

**Issue by andriyor** [ponty/pyscreenshot#64]
Is there any reason why Pillow is not at install_requires

**Comment by ponty** [comment]
1. pyscreenshot is a Linux extension of PIL/Pillow, not a standalone lib.
2. It supports both PIL and Pillow.  
3. It is a pure Python light wrapper. Pillow is C extension module, so it may start compiling C source code.

So I think that PIL/Pillow should be installed explicitly and  not hidden in the background when starting `pip install pyscreenshot`

**Comment by andriyor** [comment]
Thanks for your reply
