### ISSUE TITLE
import PIL, ModuleNotFoundError

### ISSUE THREAD

**Issue by BastienH** [ponty/pyscreenshot#70]
Hi, 
I ran into a basic issue when running pyscreenshot for the first time.
I found a sample code here : 
```
import pyscreenshot as ImageGrab
im = ImageGrab.grab()
im.save('path/to/image/folder/image_name.png')
im.show()
```
quite simple.
But it didn't work.
apparently PIL is deprecated in favor of pillow.

To solve it, I just changed the first line in the __init__ to:
```
try:
    from PIL import Image
except ModuleNotFoundError:
    from pillow import Image
```
Maybe this can be shipped in the next version?
I haven't seen that this question had history already...

Anyway thanks for this package, works great!

**Comment by ponty** [comment]
How did you install Pillow? Pillow use `PIL` for import, check the doc:
https://pillow.readthedocs.io/en/stable/handbook/tutorial.html#using-the-image-class
```python
>>> from PIL import Image
```
