### ISSUE TITLE
It can not take full screenshot of Iframe

### ISSUE THREAD

**Issue by QA-Rahul** [ponty/pyscreenshot#71]
It seems it does not take a full screenshot of the iframe. It only takes a screenshot of a portion which is visible without scroll.

I tried with following page which has all controls in iframe but could not take full screenshot. Page url : https://grapesjs.com/demo.html

**Comment by ponty** [comment]
"It only takes a screenshot of a portion which is visible without scroll."
This is correct, because this is a screenshot lib.

**Comment by QA-Rahul** [comment]
@ponty - I see. and other libraries you can suggest which can take full screenshot?

**Comment by ponty** [comment]
I don't know, search for browser screenshot libraries.
