### ISSUE TITLE
cannot import name '__version__'

### ISSUE THREAD

**Issue by helenrensiyu** [ponty/pyscreenshot#72]
I just installed pyscreenshot but while I tried to run it - there seems to be some problem with importing '__version__' from Pillow. Anyone has experienced this before? Any advice/suggestion will be appreciated! Thank you :)

> Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
> [GCC 5.4.0 20160609] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import pyscreenshot
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/helen/.local/lib/python3.5/site-packages/pyscreenshot/__init__.py", line 4, in <module>
>     from pyscreenshot.childproc import childprocess_backend_version, childprocess_grab
>   File "/home/helen/.local/lib/python3.5/site-packages/pyscreenshot/childproc.py", line 5, in <module>
>     from pyscreenshot.loader import FailedBackendError
>   File "/home/helen/.local/lib/python3.5/site-packages/pyscreenshot/loader.py", line 4, in <module>
>     from pyscreenshot import plugins
>   File "/home/helen/.local/lib/python3.5/site-packages/pyscreenshot/plugins/__init__.py", line 3, in <module>
>     from pyscreenshot.plugins import (
>   File "/home/helen/.local/lib/python3.5/site-packages/pyscreenshot/plugins/pil.py", line 1, in <module>
>     from PIL import __version__
> ImportError: cannot import name '__version__'
> >>>

**Comment by ponty** [comment]
How did you install it?
There is no such code line in `pil.py`:
```python
from PIL import version
```

https://github.com/ponty/pyscreenshot/blob/1.0/pyscreenshot/plugins/pil.py
