### ISSUE TITLE
Link to docs on pypi is broken

### ISSUE THREAD

**Issue by stuaxo** [ponty/pyscreenshot#76]
Pypi links a broken link https://pyscreenshot.readthedocs.io/

![image](https://user-images.githubusercontent.com/179677/81188123-db9f0480-8fac-11ea-9efe-a05171843958.png)

![image](https://user-images.githubusercontent.com/179677/81187986-adb9c000-8fac-11ea-81d6-eb906c99bd4b.png)

**Comment by ponty** [comment]
Fixed. Link is removed.

**Comment by stuaxo** [comment]
Thanks.
