### ISSUE TITLE
How to record screen instead of the desktop image?

### ISSUE THREAD

**Issue by ssxcxS45XT** [ponty/pyscreenshot#84]
I use the following command on Mac OS X 10.15.6. But I just record the desktop of image, instead of a screenshot. Does anybody know how to take a screenshot? Thanks.

```
import pyscreenshot
im = pyscreenshot.grab()
im.save("fullscreen.png")
```

**Comment by ponty** [comment]
Use Pillow:
https://pillow.readthedocs.io/en/latest/reference/ImageGrab.html

**Comment by ssxcxS45XT** [comment]
I found that this should be done on Mac OS X Catalina.

System Preferences -> Security & Privacy -> Screen Recording -> Terminal

https://github.com/BoboTiG/python-mss/issues/134#issuecomment-567543451
