### ISSUE TITLE
how to save clipboard image as file

### ISSUE THREAD

**Issue by sant527** [ponty/pyscreenshot#86]
I want to convert clipboard image content into an image

I tried

```
from PIL import ImageGrab
im = ImageGrab.grabclipboard() is macOS and Windows only
im.save(filename)
```
it says `ImageGrab.grabclipboard() is macOS and Windows only`

I think using this library its can be possible

**Comment by ponty** [comment]
Use latest Pillow version.
https://pillow.readthedocs.io/en/latest/reference/ImageGrab.html

You can also use this lib. Check the README
