### ISSUE TITLE
No module named 'PIL

### ISSUE THREAD

**Issue by koroner1** [ponty/pyscreenshot#88]
Hello,

There is some problem after type: 
`import pyscreenshot as ImageGrab`

error message: No module named 'PIL'

So i have to do: pip install Pillow

After i looked it is:
__init__.py -> 4 line: 
`from pyscreenshot.childproc import childprocess_backend_version`
childproc.py -> 6 line:
`from pyscreenshot.imcodec import codec`
imcodec.py -> 3 line:
`from PIL import Image`

So I think it needs to be added in: setup.py, install_requires

**Comment by ponty** [comment]
Duplicate of #64

"pyscreenshot is a Linux extension of PIL/Pillow, not a standalone lib"
