### ISSUE TITLE
Pyside6 support

### ISSUE THREAD

**Issue by MinmoTech** [ponty/pyscreenshot#90]
Could pyside6 be supported?
The api should be very similar and maybe identical to pyside2

**Comment by ponty** [comment]
Yes I plan it. Do you have a real use case for it?

**Comment by juligreen** [comment]
Yes, I'm trying to develop an OCR application and I'm using pyside6 since pyside2 is not compatible with python3.10
I would also like to support wayland so that's why I want to use pyscreenshot instead of Pillow imagegrab

**Comment by ponty** [comment]
pyside6 backend has no real value for your case. 
You don't need it on X because pillow backend works.
You can't use it on wayland but other backends may work.
I see no use cases for pyside6 backend  I may add it just to make the list complete.

**Comment by ponty** [comment]
There is no need for pyside6 back-end now. Maybe in the future.
