### ISSUE TITLE
"All backends failed" on GNOME 42

### ISSUE THREAD

**Issue by jonata** [ponty/pyscreenshot#91]
We can not use `pyscreenshot` on GNOME 42, I believe because the lack of the `gnome-screenshot` app. Do you know some command line we can use instead? If so maybe I can PR some solution. Thanks!

![image](https://user-images.githubusercontent.com/908065/166087938-d64e4036-69d4-44b7-b440-40ea1267a5c8.png)

**Comment by ponty** [comment]
Fixed
