### ISSUE TITLE
How to take screenshots on multiple screens

### ISSUE THREAD

**Issue by mndon** [ponty/pyscreenshot#93]
sane as  the all_screens param of PIL.ImageGrab

**Comment by mindonmindon** [comment]
same as the all_screens param of PIL.ImageGrab

**Comment by ponty** [comment]
See also #48 #24  #55.

I think that it is not possible  to implement such option generally, so I don't plan to add it.
What is your use case? Why can't you use PIL.ImageGrab if it has what you need?
